services:
  api_database:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"

  api_app:
    build: .
    image: api_app
    ports:
      - "8000:8000"
    depends_on:
      - api_database
    environment:
      DATABASE_URL: postgresql+psycopg://app_user:app_password@api_database:5432/app_db

volumes:
  pgdata: